### PR TITLE
Adding class element to the filter body.

### PR DESCRIPTION
**Pull request by pedrera-x**
This helps styling the size of the filter body. Allows to specify a size and scrollbar for filters with long lists of option.

Usage example
This example uses Box and tag prop together with the class to achieve a max length filter with a scroll bar (when needed)

code

<Box tag="facetfilter">
  <Filter onChange=... all=... key=... name=... active=... exclusive=... label=... inline=... choices=... />
</Box>

... custome css for the filter under the box

facetfilter .index-filter__body {
  max-height: $size-xsmall;
  overflow-y: auto;
}

@alansouzati , @ericsoderberghp could you please review, thanks Xabier P.

### CODE REVIEW

**Comment by alansouzati** [comment]
Could you please show an example on what you are trying to achieve?

Why you need to get hold of the filter body (an internal component structure) to change the height?

I would prefer change the Filter component itself to accommodate your need, hence me asking for you to describe your need in a high level.

**Comment by pedrera-x** [comment]
@alansouzati
This is an example of what is achieve with changes above...

image

Is that what you need? 
Thanks

**Comment by alansouzati** [comment]
How about adding a size option to the Filter component? @ericsoderberghp any thoughts here?

**Comment by pedrera-x** [comment]
@alansouzati , @ericsoderberghp any updates around this?

Thanks,
Xabier P.

**Comment by ericsoderberghp** [comment]
It would follow our existing Grommet patterns better to change the base behavior, rather than adding classes for additional custom CSS. Can you instead make the CSS change in grommet-index as well? I would recommend extending the examples for Filters in grommet-index-docs to illustrate the behavior in both inline and drop menu contexts.

**Comment by bryanjacquot** [comment]
@Enaitz: can you please take a look at Eric's feedback and update the PR accordingly?

**Comment by pedrera-x** [comment]
@ericsoderberghp @alansouzati I have made the change on the CSS. Can you review please? I will add the changes to index-docs (FilterDoc.js) afterwards, once the PR is satisfactory merged.

Thanks

**Comment by alansouzati** [comment]
Thanks for your contribution and welcome to our team!

**Pull request merged**
